### ISSUE TITLE
pull transform sample

### ISSUE THREAD

**Issue by phated** [nrn/redux-pull-actors#2]
I forgot what the pull-streams returned from each actor look like.  Specifically the best way to filter on actions.  If you just want to comment, I can write up an example for the readme.

**Comment by nrn** [comment]
So, each actor function gets called with the redux store, and returns a through stream or a sink stream. Every action flows into that stream with the previous and current state as an { action, before, state } object. Typically the first thing an actor will do is a `pull.filter` to scope it down to just the actions or state transitions it cares about. Often just a single action.type.

``` javascript
function actor (store) {
  return pull(
    pull.filter(function (incoming) {
      return incoming.action.type === 'add-some-to-count'
    }),
    pull.map(function (incoming) {
      return { type: 'show-difference', payload: incoming.state.count - incoming.before.count
    })
}
```

If the actor function returns a through stream, it is sunk, and whatever comes out of it is dispatched back into the redux store. If it's a sink stream it's assumed that either you are dispatching events off the store manually, or it's a side effects only stream.
